config/routes.rb
Rails.application.routes.draw do


  resources :usuarios
  resources :menus do
  	resources :productos
  end

  resources :empresas

  get 'welcome/index'

  resources :bebidas
  resources :franjas
  resources :productos
  resources :tipos
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'


  namespace :api, defaults: {format: 'json'} do
    resources :menus, only: [:index, :show]
  end
end

app/models/bebida.rb
class Bebida < ApplicationRecord
	validates :nombre, presence: {message: "^Debe ingresar un nombre"}
	validates :tipo, presence: {message: "^Debe ingresar un tipo"}
	validates :tamanio, presence: {message: "^Debe ingresar un tamaño"}
	validates :precio, presence: {message: "^Debe ingresar un precio"}
end

app/controllers/bebidas_controller.rb
class BebidasController < ApplicationController
  before_action :set_bebida, only: [:show, :edit, :update, :destroy]

  # GET /bebidas
  # GET /bebidas.json
  def index
    @bebidas = Bebida.all
  end

  # GET /bebidas/1
  # GET /bebidas/1.json
  def show
  end

  # GET /bebidas/new
  def new
    @bebida = Bebida.new
  end

  # GET /bebidas/1/edit
  def edit
  end

  # POST /bebidas
  # POST /bebidas.json
  def create
    @bebida = Bebida.new(bebida_params)
    @bebida.nombre = @bebida.nombre.upcase
    respond_to do |format|
      if @bebida.save
        format.html { redirect_to @bebida, notice: 'La Bebida se ha creado correctamente.' }
        format.json { render :show, status: :created, location: @bebida }
      else
        format.html { render :new }
        format.json { render json: @bebida.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bebidas/1
  # PATCH/PUT /bebidas/1.json
  def update
    respond_to do |format|
      if @bebida.update(bebida_params)
        format.html { redirect_to @bebida, notice: 'La Bebida se ha editado correctamente.' }
        format.json { render :show, status: :ok, location: @bebida }
      else
        format.html { render :edit }
        format.json { render json: @bebida.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bebidas/1
  # DELETE /bebidas/1.json
  def destroy
    @bebida.destroy
    respond_to do |format|
      format.html { redirect_to bebidas_url, notice: 'La Bebida se ha eliminado correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bebida
      @bebida = Bebida.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bebida_params
      params.require(:bebida).permit(:nombre, :tipo, :tamanio, :precio)
    end
end

app/helpers/bebidas_helper.rb
module BebidasHelper
end

app/views/bebidas/_bebida.html.erb
<tr>
  <td><%= bebida.nombre %></td>
  <td><%= bebida.tipo %></td>
  <td><%= bebida.tamanio %></td>
  <td><%= bebida.precio %></td>
  <td>
  <div>
  <div class="btn-group">

    
            <%= link_to '',bebida, class: 'btn btn-success btn-sm glyphicon glyphicon-eye-open', :title => "Ver" %>
            
    
    <%= link_to '', edit_bebida_path(bebida), class: 'btn btn-default btn-sm glyphicon glyphicon-pencil', :title => "Editar" %>
    
    
    <%= link_to '',
                bebida,
                method: :delete,
                class: 'btn btn-warning btn-sm glyphicon glyphicon-remove',
                data: { confirm: 'Esta seguro de eliminar esta bebida?' }, :title => "Eliminar" %>
  
  
  </div>
  </td>
</tr>

app/views/bebidas/_form.html.erb
<%= form_for(bebida) do |f| %>
  <div class="panel panel-default">
    <div class="panel-body">
      <% bebida.errors.full_messages.each do |message| %>
        <div class="alert alert-danger"><%= message %></div>
      <% end %>

      <div class="panel-body form-group">
        <p><%= f.label :nombre %></p>
        <%= f.text_field :nombre, class: 'form-control' %>
      </div>
      <div class="panel-body form-group">
        <p><%= f.label :tipo %></p>
         <%= f.select :tipo, tipo_bebidas, { include_blank: 'Seleccionar tipo de bebida' }, class: 'form-control' %>
      </div>
      <div class="panel-body form-group">
        <p><%= f.label 'Tamaño' %></p>
         <%= f.select :tamanio, tamanio_bebidas, { include_blank: 'Seleccionar tamaño' }, class: 'form-control' %>
      </div>
      
  </br>
  <div class="panel-body form-group">
    <p><%= f.label :precio %></p>
    <%= f.number_field :precio, min: 0, class: 'form-control' %>
  </div>
  </br>

    
    <div class="col-md-12">
      <div class="btn-group btn-group-justified">
        
        <div class="btn-group">
        <%= f.submit "Guardar Bebida", class: 'btn btn-info ' %>
        </div>
        <div class="btn-group">
        <%= link_to 'Cancelar', bebidas_path, class: 'btn btn-info '  %>
        </div>
      </div>
    </div>
  </div>

<% end %>

app/views/bebidas/edit.html.erb
<div class="section-container--header row">
  <div class="col-md-10 col-xs-8">
    <h2>Modificar Bebida</h2>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <%= render 'form', bebida: @bebida %>
  </div>
</div>
</br>
<div>
<%= link_to 'Volver', bebidas_path, class: 'btn btn-info btn-sm' %>
</div>

app/views/bebidas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bebidas</h1>

<div class="row">
  <div class="col-md-12">
    <div class="listing">
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Nombre</th>
              <th>Tipo</th>
              <th>Tamaño</th>
              <th>Precio</th>
              <th colspan="3"></th>
            </tr>
          </thead>

  
        <tbody>
                <%= render @bebidas %>
        </tbody>
      </table>

      </div>
    </div>
  </div>
  </div>

<br>
<div class="col-md-12">
  <div class="btn-group btn-group-justified">
    <%= link_to 'Nueva Bebida', new_bebida_path, class: 'btn btn-default'  %>
  
    <%= link_to 'Volver', root_path, class: 'btn btn-default' %>

  </div>
</div>

app/views/bebidas/new.html.erb
<div class="section-container--header row">
  <div class="col-md-10 col-xs-8">
    <h2>Nueva Bebida</h2>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <%= render 'form', bebida: @bebida %>
  </div>
</div>

app/views/bebidas/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Nombre:</strong>
  <%= @bebida.nombre %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @bebida.tipo %>
</p>

<p>
  <strong>Tamaño:</strong>
  <%= @bebida.tamanio %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @bebida.precio %>
</p>
<div class="btn-group-vertical">
<%= link_to 'Editar', edit_bebida_path(@bebida), class: 'btn btn-default' %> 
<%= link_to 'Volver', bebidas_path, class: 'btn btn-info' %>
</div>