config/routes.rb
Rails.application.routes.draw do


  resources :usuarios
  resources :menus do
  	resources :productos
  end

  resources :empresas

  get 'welcome/index'

  resources :bebidas
  resources :franjas
  resources :productos
  resources :tipos
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'


  namespace :api, defaults: {format: 'json'} do
    resources :menus, only: [:index, :show]
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<h2>Hola Administrador!</h2>



 
</br>
<div>
  <ul class="list-unstyled">
    <li class><%= link_to 'Tipos de Producto', tipos_path, class: 'btn btn-default btn-lg btn-block' %></li>
    </br>
      	
    <li><%= link_to 'Productos', productos_path, class: 'btn btn-default btn-lg btn-block'  %></li>
    </br>
      
    <li><%= link_to 'Bebidas', bebidas_path, class: 'btn btn-default btn-lg btn-block'  %></li>
    </br>

    <li><%= link_to 'Franjas', franjas_path, class: 'btn btn-default btn-lg btn-block'  %></li>
    </br>
    <li><%= link_to 'Empresas', empresas_path, class: 'btn btn-default btn-lg btn-block'  %></li>
    </br>
    <li><%= link_to 'Menus', menus_path, class: 'btn btn-default btn-lg btn-block'  %></li>
    </br>
    <li><%= link_to 'Usuarios', usuarios_path, class: 'btn btn-default btn-lg btn-block'  %></li>
    </br>
  </ul>	
</div>


 <%= render 'footer' %>