config/routes.rb
Rails.application.routes.draw do


  resources :usuarios
  resources :menus do
  	resources :productos
  end

  resources :empresas

  get 'welcome/index'

  resources :bebidas
  resources :franjas
  resources :productos
  resources :tipos
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'


  namespace :api, defaults: {format: 'json'} do
    resources :menus, only: [:index, :show]
  end
end

app/models/producto.rb
class Producto < ApplicationRecord
	has_many :tiene_productos
	has_many :menus, through: :tiene_productos
	belongs_to :tipo, optional: true
	
	validates :nombre, presence: {message: "^Debe ingresar un nombre"}
	validates :descripcion, presence: {message: "^Debe ingresar una descripción"}
	validates :tipo_id, presence: {message: "^Debe seleccionar un tipo"}
	validates :precio, presence: {message: "^Debe indicar un precio"}
	
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  before_action :set_producto, only: [:show, :edit, :update]

  # GET /productos
  # GET /productos.json
  def index
    @productos = Producto.all
    @tipos = Tipo.all
  end


  # GET /productos/1
  # GET /productos/1.json
  def show    
  end

  # GET /productos/new
  def new
    @producto = Producto.new
  end

  # GET /productos/1/edit
  def edit
  end

  # POST /productos
  # POST /productos.json
  def create
    @producto = Producto.new(producto_params)
    @producto.nombre = @producto.nombre.upcase
    respond_to do |format|
      if @producto.save
        format.html { redirect_to @producto, notice: 'El Producto se ha creado correctamente.' }
        format.json { render :show, status: :created, location: @producto }
      else
        format.html { render :new }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /productos/1
  # PATCH/PUT /productos/1.json
  def update
    respond_to do |format|
      if @producto.update(producto_params)
        format.html { redirect_to @producto, notice: 'El Producto se ha editado correctamente.' }
        format.json { render :show, status: :ok, location: @producto }
      else
        format.html { render :edit }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos/1
  # DELETE /productos/1.json
  def destroy
    # @producto.destroy
    # respond_to do |format|
    #   format.html { redirect_to productos_url, notice: 'Producto was successfully destroyed.' }
    #   format.json { head :no_content }
    # end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producto
      @producto = Producto.find(params[:id])
      
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def producto_params
      params.require(:producto).permit(:nombre, :descripcion, :tipo_id, :precio)
    end
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/views/productos/_form.html.erb
<%= form_for(producto) do |f| %>
  <div class="panel panel-default">
    <div class="panel-body">
      <% producto.errors.full_messages.each do |message| %>
        <div class="alert alert-danger"><%= message %></div>
      <% end %>

      <div class="panel-body form-group">
        <p><%= f.label :nombre %></p>
        <%= f.text_field :nombre, class: 'form-control' %>
      </div>
      <div class="panel-body form-group">
        <p><%= f.label :descripcion %></p>
    <%= f.text_area :descripcion, class: 'form-control' %>
      </div>
      <div class="panel-body form-group">
    <p><%= f.label :tipo_id %></p>
    <%= f.select :tipo_id,  Tipo.all.collect {|t| [ t.nombre, t.id ] }, { include_blank: 'Seleccionar Tipo de Producto' }, class: 'form-control' %>
  </div>
  </br>
  <div class="panel-body form-group">
    <p><%= f.label :precio %></p>
    <%= f.number_field :precio, :step => "0.5", min: 0, class: 'form-control' %>
  </div>
  </br>
    <div class="col-md-12">
      <div class="btn-group btn-group-justified">
        
        <div class="btn-group">
        <%= f.submit "Guardar Producto", class: 'btn btn-info ' %>
        </div>
        <div class="btn-group">
        <%= link_to 'Cancelar', productos_path, class: 'btn btn-info'  %>
        </div>
      </div>
    </div>
<% end %>

    

app/views/productos/_producto.html.erb
<tr>
  <td><%= producto.nombre %></td>
  <td><%= producto.descripcion %></td>
  <td><%= producto.tipo.nombre if producto.tipo %></td>
  <td><%= producto.precio %></td>
  <td>
  <div class="btn-group">
    <%= link_to '', producto, class: 'btn btn-success btn-sm glyphicon glyphicon-eye-open', :title => "Ver"'' %>
    <%= link_to '', edit_producto_path(producto), class: 'btn btn-default btn-sm glyphicon glyphicon-pencil', :title => "Editar" %>
    
  </div>
  </td>
</tr>

app/views/productos/edit.html.erb
<div class="section-container--header row">
  <div class="col-md-10 col-xs-8">
    <h2>Modificar Producto</h2>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <%= render 'form', producto: @producto %>
  </div>
</div>
</br>
<div>
<%= link_to 'Volver', productos_path, class: 'btn btn-info btn-sm' %>
</div>

app/views/productos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Productos</h1>

<div class="row">
  <div class="col-md-12">
    <div class="listing">
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Nombre</th>
              <th>Descripcion</th>
              <th>Tipo de Producto</th>
              <th>Precio</th>
              <th colspan="3"></th>
            </tr>
        </thead>
      
        <tbody>
                <%= render @productos %>
        </tbody>
      </table>

      </div>
    </div>
  </div>
  </div>

<br><div class="col-md-12">
  <div class="btn-group btn-group-justified">
    <%= link_to 'Nuevo Producto', new_producto_path, class: 'btn btn-default'  %>
  
    <%= link_to 'Volver', root_path, class: 'btn btn-default' %>

  </div>
</div>

app/views/productos/new.html.erb
<div class="section-container--header row">
  <div class="col-md-10 col-xs-8">
    <h2>Nuevo Producto</h2>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <%= render 'form', producto: @producto %>
  </div>
</div>

app/views/productos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @producto.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @producto.descripcion %>
</p>
<p>
  <strong>Tipo de producto:</strong>
  <%= @producto.tipo.nombre if @producto.tipo%>
</p>
<p>
  <strong>Precio:</strong>
  <%= @producto.precio %>
</p>
<div class="btn-group-vertical">
<%= link_to 'Editar', edit_producto_path(@producto), class: 'btn btn-default' %> 
<%= link_to 'Volver', productos_path, class: 'btn btn-info' %>
</div>