config/routes.rb
Rails.application.routes.draw do


  resources :usuarios
  resources :menus do
  	resources :productos
  end

  resources :empresas

  get 'welcome/index'

  resources :bebidas
  resources :franjas
  resources :productos
  resources :tipos
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'


  namespace :api, defaults: {format: 'json'} do
    resources :menus, only: [:index, :show]
  end
end

app/models/franja.rb
class Franja < ApplicationRecord

	
	validates :segunda_hasta, presence: true
	validates :primera_precio, presence: true
	validates :segunda_precio, presence: true
	validates :tercera_precio, presence: true



	validates :primera_hasta, presence: true,
		numericality: { less_than: :segunda_hasta, message: "^Debe ser menor a la segunda franja de sueldos" }
	validates :segunda_hasta, numericality: { greater_than: :primera_hasta, message: "^Debe ser mayor a la primera franja de sueldos" }
	validates :primera_precio, numericality: { less_than: :segunda_precio, message: "^Debe ser menor a precio de segunda franja sueldos" }
  	validates :segunda_precio, numericality: { greater_than_or_equal: :primera_precio, less_than: :tercera_precio, message: "^Debe ser mayor a precio de primera franja  y menor a precio de tercera franja de sueldos" }
	validates :tercera_precio, numericality: { greater_than: :segunda_precio, message: "^Debe ser mayor a precio de segunda franja sueldos" }
	



end

app/controllers/franjas_controller.rb
class FranjasController < ApplicationController
  before_action :set_franja, only: [:show, :edit, :update, :destroy]

  # GET /franjas
  # GET /franjas.json
  def index
    @franjas = Franja.all
  end

  # GET /franjas/1
  # GET /franjas/1.json
  def show
  end

  # GET /franjas/new
  def new
    @franja = Franja.new
  end

  # GET /franjas/1/edit
  def edit
  end

  # POST /franjas
  # POST /franjas.json
  def create
    @franja = Franja.new(franja_params)
    @franja.fecha = Time.now
    if @franja.primera_hasta==nil  
        @franja.primera_hasta=0
    end
    if @franja.primera_precio==nil 
      @franja.primera_precio=0
    end
    if @franja.segunda_hasta==nil
      @franja.segunda_hasta=0
    end
    if @franja.segunda_precio==nil
      @franja.segunda_precio=0
    end
    if @franja.tercera_precio==nil
      @franja.tercera_precio=0
    end
    respond_to do |format|
      if @franja.save
        format.html { redirect_to @franja, notice: 'La Franja se ha creado correctamente.' }
        format.json { render :show, status: :created, location: @franja }
      else
        format.html { render :new }
        format.json { render json: @franja.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /franjas/1
  # PATCH/PUT /franjas/1.json
  def update
    respond_to do |format|
      if @franja.update(franja_params)
        format.html { redirect_to @franja, notice: 'La Franja se ha editado correctamente.' }
        format.json { render :show, status: :ok, location: @franja }
      else
        format.html { render :edit }
        format.json { render json: @franja.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /franjas/1
  # DELETE /franjas/1.json
  def destroy
    @franja.destroy
    respond_to do |format|
      format.html { redirect_to franjas_url, notice: 'La Franja se elimino correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_franja
      @franja = Franja.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def franja_params
      params.require(:franja).permit(:fecha, :primera_hasta, :primera_precio, :segunda_hasta, :segunda_precio, :tercera_precio)
    end
end

app/helpers/franjas_helper.rb
module FranjasHelper
end

app/views/franjas/_form.html.erb
<%= form_for(franja) do |f| %>
  <div class="panel panel-default">
    <div class="panel-body">
      <% franja.errors.full_messages.each do |message| %>
        <div class="alert alert-danger"><%= message %></div>
      <% end %>

      <div class="panel-body form-group">
        <p><%= f.label "Primera franja, sueldos hasta: " %></p>
        <%= f.number_field :primera_hasta,min:0, class: 'form-control' %>
      </div>
      <div class="panel-body form-group">
        <p><%= f.label "Valor del ticket primera franja: " %></p>
        <%= f.number_field :primera_precio, min:0, class: 'form-control' %>
      </div>
      <div class="panel-body form-group">
      <p><%= f.label "Segunda franja, sueldos hasta: " %></p>
      <%= f.number_field :segunda_hasta, min:0, class: 'form-control' %>
  </div>
  
  <div class="panel-body form-group">
    <p><%= f.label "Valor del ticket segunda franja: " %></p>
    <%= f.number_field :segunda_precio, min:0, class: 'form-control' %>
  </div>
    <div class="panel-body form-group">
    <p><%= f.label "Valor del ticket para sueldos mayores: " %></p>
    <%= f.number_field :tercera_precio, min:0, class: 'form-control' %>
  </div>
  </br>
    <div class="col-md-12">
      <div class="btn-group btn-group-justified">
        
        <div class="btn-group">
        <%= f.submit "Guardar Franja", class: 'btn btn-info ' %>
        </div>
        <div class="btn-group">
        <%= link_to 'Cancelar', franjas_path, class: 'btn btn-info '  %>
        </div>
      </div>
    </div>
    
  </div>
<% end %>

    

app/views/franjas/_franja.html.erb
<tr>
  <td><%= franja.fecha.to_formatted_s(:short)  %></td>
  <td><%= franja.primera_hasta %></td>
  <td><%= franja.primera_precio %></td>
  <td><%= franja.segunda_hasta %></td>
  <td><%= franja.segunda_precio %></td>
  <td><%= franja.segunda_hasta %></td>
  <td><%= franja.tercera_precio %></td>

  <td>
  <div class="btn-group">
    <%= link_to '', franja, class: 'btn btn-success btn-sm glyphicon glyphicon-eye-open', :title => "Ver" %>
    <%= link_to '', edit_franja_path(franja), class: 'btn btn-default btn-sm glyphicon glyphicon-pencil', :title => "Editar" %>
    <%= link_to '',
                franja,
                method: :delete,
                class: 'btn btn-warning btn-sm glyphicon glyphicon-remove',
                data: { confirm: 'Esta seguro de eliminar esta franja?' }, :title => "Eliminar" %>
  </div>
  </td>
</tr>

app/views/franjas/edit.html.erb
<div class="section-container--header row">
  <div class="col-md-10 col-xs-8">
    <h2>Modificar Franja</h2>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <%= render 'form', franja: @franja %>
  </div>
</div>
</br>
<div>
<%= link_to 'Volver', franjas_path, class: 'btn btn-info btn-sm' %>
</div>

app/views/franjas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Franjas</h1>

<div class="row">
  <div class="col-md-15">
    <div class="listing">
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Fecha</th>
              <th>Sueldos hasta</th>
              <th>Valor del ticket</th>
              <th>Sueldos hasta</th>
              <th>Valor del ticket</th>
              <th>Sueldos mayores a</th>
              <th>Valor del ticket</th>
              <th colspan="3"></th>
            </tr>
       </thead>

  
        <tbody>
                <%= render @franjas %>
        </tbody>
      </table>

      </div>
    </div>
  </div>
  </div>

<br>
<div class="col-md-12">
  <div class="btn-group btn-group-justified">
    <%= link_to 'Nueva Franja', new_franja_path, class: 'btn btn-default'  %>
  
    <%= link_to 'Volver', root_path, class: 'btn btn-default' %>

  </div>
</div>

app/views/franjas/new.html.erb
<div class="section-container--header row">
  <div class="col-md-10 col-xs-8">
    <h2>Nueva Franja</h2>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <%= render 'form', franja: @franja %>
  </div>
</div>

app/views/franjas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fecha:</strong>
  <%= @franja.fecha.to_formatted_s(:short) %>
</p>

<p>
  <strong>Sueldos hasta:</strong>
  <%= @franja.primera_hasta %>
</p>

<p>
  <strong>Valor del ticket:</strong>
  <%= @franja.primera_precio %>
</p>

<p>
  <strong>Sueldos mayores a </strong><%= @franja.primera_hasta %><strong> y hasta:</strong>
  <%= @franja.segunda_hasta %>
</p>

<p>
  <strong>Valor del ticket:</strong>
  <%= @franja.segunda_precio %>
</p>
<p>
  <strong>Sueldos mayores a </strong><%= @franja.segunda_hasta %>
</p>
<p>
  <strong>Valor del ticket:</strong>
  <%= @franja.tercera_precio %>
</p>
</br>
<div class="btn-group-vertical">
<%= link_to 'Editar', edit_franja_path(@franja), class: 'btn btn-default' %> 
<%= link_to 'Volver', franjas_path, class: 'btn btn-info' %>
</div>